CREATE DATABASE SchoolDB;

USE SchoolDB;
GO

CREATE TABLE Contact (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NULL,
    Surname NVARCHAR(100) NULL
    /*IdAdress INT FOREIGN KEY*/ ,
);

SELECT * FROM Contact;

CREATE TABLE Address(
Id INT IDENTITY(1,1) PRIMARY KEY,
Street NVARCHAR(60) NULL,
City NVARCHAR(15) NULL,
PostalCode NVARCHAR (10) NULL,
);
SELECT * FROM Address;